/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrgId = IDL.Nat;
export const VendorId = IDL.Nat;
export const Time = IDL.Int;
export const Vendor = IDL.Record({
  'id' : VendorId,
  'contactInfo' : IDL.Text,
  'orgId' : OrgId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const AppId = IDL.Nat;
export const ActivityLog = IDL.Record({
  'id' : AppId,
  'appId' : AppId,
  'orgId' : OrgId,
  'metadata' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'activeOrgId' : IDL.Opt(OrgId),
});
export const PricingPlan = IDL.Record({
  'id' : OrgId,
  'features' : IDL.Vec(IDL.Text),
  'isPublished' : IDL.Bool,
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'user' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createOrganization' : IDL.Func([IDL.Text, IDL.Text], [OrgId], []),
  'createPlan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
      [OrgId],
      [],
    ),
  'createVendor' : IDL.Func(
      [OrgId, IDL.Text, IDL.Text, IDL.Text],
      [VendorId],
      [],
    ),
  'deactivateVendor' : IDL.Func([VendorId], [], []),
  'deleteOrganization' : IDL.Func([OrgId], [], []),
  'getActiveVendors' : IDL.Func([OrgId], [IDL.Vec(Vendor)], ['query']),
  'getActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDashboardMetrics' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
    ),
  'getOrganization' : IDL.Func(
      [OrgId],
      [
        IDL.Record({
          'id' : OrgId,
          'members' : IDL.Vec(IDL.Principal),
          'vendors' : IDL.Vec(VendorId),
          'owner' : IDL.Principal,
          'name' : IDL.Text,
          'createdAt' : Time,
          'admins' : IDL.Vec(IDL.Principal),
        }),
      ],
      ['query'],
    ),
  'getPublishedPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([OrgId, IDL.Principal], [UserRole], ['query']),
  'getVendor' : IDL.Func([VendorId], [Vendor], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinOrganization' : IDL.Func([OrgId], [], []),
  'listOrganizations' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : OrgId,
            'members' : IDL.Vec(IDL.Principal),
            'vendors' : IDL.Vec(VendorId),
            'owner' : IDL.Principal,
            'name' : IDL.Text,
            'createdAt' : Time,
            'admins' : IDL.Vec(IDL.Principal),
          })
        ),
      ],
      ['query'],
    ),
  'listPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'listVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'logActivity' : IDL.Func([OrgId, AppId, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrgId = IDL.Nat;
  const VendorId = IDL.Nat;
  const Time = IDL.Int;
  const Vendor = IDL.Record({
    'id' : VendorId,
    'contactInfo' : IDL.Text,
    'orgId' : OrgId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const AppId = IDL.Nat;
  const ActivityLog = IDL.Record({
    'id' : AppId,
    'appId' : AppId,
    'orgId' : OrgId,
    'metadata' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'activeOrgId' : IDL.Opt(OrgId),
  });
  const PricingPlan = IDL.Record({
    'id' : OrgId,
    'features' : IDL.Vec(IDL.Text),
    'isPublished' : IDL.Bool,
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'user' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createOrganization' : IDL.Func([IDL.Text, IDL.Text], [OrgId], []),
    'createPlan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
        [OrgId],
        [],
      ),
    'createVendor' : IDL.Func(
        [OrgId, IDL.Text, IDL.Text, IDL.Text],
        [VendorId],
        [],
      ),
    'deactivateVendor' : IDL.Func([VendorId], [], []),
    'deleteOrganization' : IDL.Func([OrgId], [], []),
    'getActiveVendors' : IDL.Func([OrgId], [IDL.Vec(Vendor)], ['query']),
    'getActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDashboardMetrics' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
      ),
    'getOrganization' : IDL.Func(
        [OrgId],
        [
          IDL.Record({
            'id' : OrgId,
            'members' : IDL.Vec(IDL.Principal),
            'vendors' : IDL.Vec(VendorId),
            'owner' : IDL.Principal,
            'name' : IDL.Text,
            'createdAt' : Time,
            'admins' : IDL.Vec(IDL.Principal),
          }),
        ],
        ['query'],
      ),
    'getPublishedPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([OrgId, IDL.Principal], [UserRole], ['query']),
    'getVendor' : IDL.Func([VendorId], [Vendor], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinOrganization' : IDL.Func([OrgId], [], []),
    'listOrganizations' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : OrgId,
              'members' : IDL.Vec(IDL.Principal),
              'vendors' : IDL.Vec(VendorId),
              'owner' : IDL.Principal,
              'name' : IDL.Text,
              'createdAt' : Time,
              'admins' : IDL.Vec(IDL.Principal),
            })
          ),
        ],
        ['query'],
      ),
    'listPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
    'listVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'logActivity' : IDL.Func([OrgId, AppId, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };