/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : AppId,
  'appId' : AppId,
  'orgId' : OrgId,
  'metadata' : string,
  'user' : Principal,
  'timestamp' : Time,
  'eventType' : string,
}
export type AppId = bigint;
export type OrgId = bigint;
export interface PricingPlan {
  'id' : OrgId,
  'features' : Array<string>,
  'isPublished' : boolean,
  'name' : string,
  'lastUpdated' : Time,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'activeOrgId' : [] | [OrgId],
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : VendorId,
  'contactInfo' : string,
  'orgId' : OrgId,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
}
export type VendorId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createOrganization' : ActorMethod<[string, string], OrgId>,
  'createPlan' : ActorMethod<
    [string, string, bigint, Array<string>, string],
    OrgId
  >,
  'createVendor' : ActorMethod<[OrgId, string, string, string], VendorId>,
  'deactivateVendor' : ActorMethod<[VendorId], undefined>,
  'deleteOrganization' : ActorMethod<[OrgId], undefined>,
  'getActiveVendors' : ActorMethod<[OrgId], Array<Vendor>>,
  'getActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDashboardMetrics' : ActorMethod<[], [bigint, bigint, bigint, bigint]>,
  'getOrganization' : ActorMethod<
    [OrgId],
    {
      'id' : OrgId,
      'members' : Array<Principal>,
      'vendors' : Array<VendorId>,
      'owner' : Principal,
      'name' : string,
      'createdAt' : Time,
      'admins' : Array<Principal>,
    }
  >,
  'getPublishedPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[OrgId, Principal], UserRole>,
  'getVendor' : ActorMethod<[VendorId], Vendor>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinOrganization' : ActorMethod<[OrgId], undefined>,
  'listOrganizations' : ActorMethod<
    [],
    Array<
      {
        'id' : OrgId,
        'members' : Array<Principal>,
        'vendors' : Array<VendorId>,
        'owner' : Principal,
        'name' : string,
        'createdAt' : Time,
        'admins' : Array<Principal>,
      }
    >
  >,
  'listPlans' : ActorMethod<[], Array<PricingPlan>>,
  'listVendors' : ActorMethod<[], Array<Vendor>>,
  'logActivity' : ActorMethod<[OrgId, AppId, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];