/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InteropContext {
    userRole?: UserRole;
    activeOrg?: OrgId;
    caller: Principal;
    authenticated: boolean;
    profile?: UserProfile;
}
export type AppId = bigint;
export type OrgId = bigint;
export type Time = bigint;
export interface ActivityLog {
    id: AppId;
    appId: AppId;
    orgId: OrgId;
    metadata: string;
    user: Principal;
    timestamp: Time;
    eventType: string;
}
export interface PricingPlan {
    id: OrgId;
    features: Array<string>;
    isPublished: boolean;
    name: string;
    lastUpdated: Time;
    description: string;
    category: string;
    price: bigint;
}
export interface Vendor {
    id: VendorId;
    contactInfo: string;
    orgId: OrgId;
    name: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
}
export type VendorId = bigint;
export interface UserProfile {
    name: string;
    email: string;
    activeOrgId?: OrgId;
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createOrganization(name: string, callerEmail: string): Promise<OrgId>;
    createPlan(name: string, description: string, price: bigint, features: Array<string>, category: string): Promise<OrgId>;
    createVendor(orgId: OrgId, name: string, description: string, contactInfo: string): Promise<VendorId>;
    deactivateVendor(vendorId: VendorId): Promise<void>;
    deleteOrganization(orgId: OrgId): Promise<void>;
    getActiveVendors(orgId: OrgId): Promise<Array<Vendor>>;
    getActivityLogs(): Promise<Array<ActivityLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDashboardMetrics(): Promise<[bigint, bigint, bigint, bigint]>;
    getInteropContext(): Promise<InteropContext>;
    getOrganization(orgId: OrgId): Promise<{
        id: OrgId;
        members: Array<Principal>;
        vendors: Array<VendorId>;
        owner: Principal;
        name: string;
        createdAt: Time;
        admins: Array<Principal>;
    }>;
    getPublishedPlans(): Promise<Array<PricingPlan>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(orgId: OrgId, user: Principal): Promise<UserRole>;
    getVendor(vendorId: VendorId): Promise<Vendor>;
    isCallerAdmin(): Promise<boolean>;
    joinOrganization(orgId: OrgId): Promise<void>;
    listOrganizations(): Promise<Array<{
        id: OrgId;
        members: Array<Principal>;
        vendors: Array<VendorId>;
        owner: Principal;
        name: string;
        createdAt: Time;
        admins: Array<Principal>;
    }>>;
    listPlans(): Promise<Array<PricingPlan>>;
    listVendors(): Promise<Array<Vendor>>;
    logActivity(orgId: OrgId, appId: AppId, eventType: string, metadata: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { InteropContext as _InteropContext, OrgId as _OrgId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrganization(arg0: string, arg1: string): Promise<OrgId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrganization(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrganization(arg0, arg1);
            return result;
        }
    }
    async createPlan(arg0: string, arg1: string, arg2: bigint, arg3: Array<string>, arg4: string): Promise<OrgId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlan(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlan(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createVendor(arg0: OrgId, arg1: string, arg2: string, arg3: string): Promise<VendorId> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deactivateVendor(arg0: VendorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateVendor(arg0);
            return result;
        }
    }
    async deleteOrganization(arg0: OrgId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrganization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrganization(arg0);
            return result;
        }
    }
    async getActiveVendors(arg0: OrgId): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveVendors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveVendors(arg0);
            return result;
        }
    }
    async getActivityLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<[bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return [
                result[0],
                result[1],
                result[2],
                result[3]
            ];
        }
    }
    async getInteropContext(): Promise<InteropContext> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteropContext();
                return from_candid_InteropContext_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteropContext();
            return from_candid_InteropContext_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganization(arg0: OrgId): Promise<{
        id: OrgId;
        members: Array<Principal>;
        vendors: Array<VendorId>;
        owner: Principal;
        name: string;
        createdAt: Time;
        admins: Array<Principal>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganization(arg0);
            return result;
        }
    }
    async getPublishedPlans(): Promise<Array<PricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPlans();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: OrgId, arg1: Principal): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0, arg1);
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0, arg1);
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: VendorId): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinOrganization(arg0: OrgId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinOrganization(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinOrganization(arg0);
            return result;
        }
    }
    async listOrganizations(): Promise<Array<{
        id: OrgId;
        members: Array<Principal>;
        vendors: Array<VendorId>;
        owner: Principal;
        name: string;
        createdAt: Time;
        admins: Array<Principal>;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrganizations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrganizations();
            return result;
        }
    }
    async listPlans(): Promise<Array<PricingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlans();
            return result;
        }
    }
    async listVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVendors();
            return result;
        }
    }
    async logActivity(arg0: OrgId, arg1: AppId, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_InteropContext_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InteropContext): InteropContext {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrgId]): OrgId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userRole: [] | [_UserRole];
    activeOrg: [] | [_OrgId];
    caller: Principal;
    authenticated: boolean;
    profile: [] | [_UserProfile];
}): {
    userRole?: UserRole;
    activeOrg?: OrgId;
    caller: Principal;
    authenticated: boolean;
    profile?: UserProfile;
} {
    return {
        userRole: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.userRole)),
        activeOrg: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.activeOrg)),
        caller: value.caller,
        authenticated: value.authenticated,
        profile: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    activeOrgId: [] | [_OrgId];
}): {
    name: string;
    email: string;
    activeOrgId?: OrgId;
} {
    return {
        name: value.name,
        email: value.email,
        activeOrgId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.activeOrgId))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "owner" in value ? UserRole.owner : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    activeOrgId?: OrgId;
}): {
    name: string;
    email: string;
    activeOrgId: [] | [_OrgId];
} {
    return {
        name: value.name,
        email: value.email,
        activeOrgId: value.activeOrgId ? candid_some(value.activeOrgId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
